# CodeBuild BuildSpec file, this will install all the tools needed to deploy the app

version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - bash ./submodules/ensolvers-cicd/utils/codebuild_environment_configuration_commands.sh

  build:
    commands:
      - bash ./submodules/ensolvers-cicd/spring-boot-deploy-ecs.sh $APPS
