AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EcsClusterName:
    Type: String
    Default: ENVIRONMENT-AppName
    Description: Name of the cluster
  Role:
    Type: String
    Default: arn:aws:iam::NNNNNNNNNNNNNN:role/ecsTaskExecutionRole
    Description: >-
      An IAM role to give the service's containers if the code within
      needs to access other AWS resources like S3 buckets, DynamoDB tables, etc
  DesiredCount:
    Type: Number
    Default: 1
    Description: How many copies of the service task to run
  ContainerServiceName:
    Type: String
    Default: webapp
    Description: A name for the service
  DockerImage:
    Type: String
    Default: nginx
    Description: The docker image ref, it could be a Docker ECR Repository URI or a standard Dockerhub image
  HealthCheckGracePeriodSeconds:
    Type: String
    Default: 300
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port number the application inside the docker container is binding to
  ContainerCpu:
    Type: Number
    Default: 1024
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 8192
    Description: How much memory in megabytes to give the container - check https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html for valid CPU/Memory combinations
  SourceCidr:
    Type: String
    Description: >-
      Optional - CIDR/IP range for EcsPort and ContainerPort - defaults to
      0.0.0.0/0
    Default: 0.0.0.0/0
  VPC:
    Type: String
    Description: Id of the VPC
    Default: vpc-3a54a840	
  Subnet1Id:
    Type: String
    Description: Id of the Subnet
    Default: subnet-1db31a7a
  Subnet2Id:
    Type: String
    Description: Id of the Subnet
    Default: subnet-546e926a
  LoadBalancerType:
    Type: String
    Default: 'internet-facing'
    AllowedValues: ['internet-facing', 'internal']
    Description: If the ELB will be available publicly (internet-facing) or if it is a private one (internal)
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref EcsClusterName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 48c73587-7802-47c3-bdb1-5feae716e743
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Ref EcsClusterName
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
      - FARGATE
      ExecutionRoleArn: !Ref Role
      TaskRoleArn: !Ref Role
      ContainerDefinitions:
      - Name: !Ref ContainerServiceName
        Cpu: !Ref ContainerCpu
        Memory: !Ref ContainerMemory
        Image: !Ref DockerImage
        PortMappings:
        - ContainerPort: !Ref ContainerPort
        LogConfiguration:
          LogDriver: "awslogs"
          Options:
              "awslogs-group": !Ref EcsClusterName
              "awslogs-region": us-east-1
              "awslogs-stream-prefix": !Ref EcsClusterName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 63a3cdfd-32ba-4e1c-b51f-5354d49579f5
  EcsElasticLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Join
      - '-'
      - - !Ref 'AWS::StackName'
        - ELB
      SecurityGroups:
      - !Ref EcsSecurityGroup
      Subnets:
      - !Ref Subnet1Id
      - !Ref Subnet2Id
      Scheme: !Ref LoadBalancerType
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d8a3f351-c0a9-4586-b1c3-cd456d7670c5
  PublicLoadBalancerListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref EcsElasticLoadBalancer
      Port: !Ref ContainerPort
      Protocol: HTTP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref TargetGroupPublic
    DependsOn:
    - TargetGroupPublic
    - EcsElasticLoadBalancer
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 478f4ccb-6346-4e5d-aed7-b267b29bbd7c
  EcsService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      HealthCheckGracePeriodSeconds: !Ref HealthCheckGracePeriodSeconds
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - !Ref EcsSecurityGroup
          Subnets:
          - !Ref Subnet1Id
      LoadBalancers:
      - ContainerName: !Ref ContainerServiceName
        ContainerPort: '80'
        TargetGroupArn: !Ref TargetGroupPublic
      ServiceName: !Ref EcsClusterName
    DependsOn:
    - ECSCluster
    - TaskDefinition
    - PublicLoadBalancerListener
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4af87866-85eb-4850-bef8-e050ab840370
  TargetGroupPublic:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: !Ref VPC
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /status
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
    DependsOn: EcsElasticLoadBalancer
    Metadata:
      'AWS::CloudFormation::Designer':
        id: edd8aacb-9ea2-4f44-8180-a0d720a0c405
  EcsSecurityGroupHTTPinbound:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: !Ref SourceCidr
  EcsSecurityGroupOutbound:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      IpProtocol: tcp
      FromPort: '0'
      ToPort: '65535'
      CidrIp: !Ref SourceCidr
      GroupId: !Ref EcsSecurityGroup
  EcsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: ECS Allowed Ports
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 44b5b0f4-abca-42d7-806c-3586fe6809d0
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Ref EcsClusterName
      RetentionInDays: 7
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7d7d02ec-ba16-41cd-b11f-046129c6c2d1
Outputs:
  Version:
    Description: ECS Cloudformation template version
    Value: 3.0.0
  StackName:
    Value: !Ref 'AWS::StackName'
  PublicListener:
    Description: The ARN of the public load balancer's Listener
    Value: !Ref PublicLoadBalancerListener
    Export:
      Name: !Join
      - '-'
      - - !Ref 'AWS::StackName'
        - PublicListener
  EcsSecurityGroup:
    Description: A security group used to allow Fargate containers to receive traffic
    Value: !Ref EcsSecurityGroup
    Export:
      Name: !Join
      - '-'
      - - !Ref 'AWS::StackName'
        - EcsSecurityGroup
Metadata:
  'AWS::CloudFormation::Designer':
    44b5b0f4-abca-42d7-806c-3586fe6809d0:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    d8a3f351-c0a9-4586-b1c3-cd456d7670c5:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
      - 44b5b0f4-abca-42d7-806c-3586fe6809d0
    edd8aacb-9ea2-4f44-8180-a0d720a0c405:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 210
      z: 1
      embeds: []
      dependson:
      - d8a3f351-c0a9-4586-b1c3-cd456d7670c5
    478f4ccb-6346-4e5d-aed7-b267b29bbd7c:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
      dependson:
      - d8a3f351-c0a9-4586-b1c3-cd456d7670c5
    63a3cdfd-32ba-4e1c-b51f-5354d49579f5:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 90
      z: 1
      embeds: []
    48c73587-7802-47c3-bdb1-5feae716e743:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 210
      z: 1
      embeds: []
    4af87866-85eb-4850-bef8-e050ab840370:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 330
      z: 1
      embeds: []
      isassociatedwith:
      - edd8aacb-9ea2-4f44-8180-a0d720a0c405
      dependson:
      - 478f4ccb-6346-4e5d-aed7-b267b29bbd7c
      - 48c73587-7802-47c3-bdb1-5feae716e743
      - 63a3cdfd-32ba-4e1c-b51f-5354d49579f5
    7d7d02ec-ba16-41cd-b11f-046129c6c2d1:
      size:
        width: 140
        height: 140
      position:
        x: -250
        'y': 180
      z: 0