#!/bin/bash

export APP_NAME="<TO_COMPLETE>"
export MODULE_NAME="<TO_COMPLETE>"
export CLUSTER_NAME="<TO_COMPLETE>"
export VCPU=<NUMBER_TO_COMPLETE>
export MEMORY=<NUMBER_TO_COMPLETE>
export SERVER_PORT=<NUMBER_TO_COMPLETE>