#!/bin/bash

export ECS_TASK_EXECUTION_ROLE="<TO_COMPLETE>"
export DOCKER_IMAGE="<TO_COMPLETE>"
export AWS_REGION="<TO_COMPLETE>"
export S3_BUCKET_NAME="<TO_COMPLETE>"
export AWS_SECRET_MANAGER_SECRET_ARN="<OPTIONAL>"
