AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EKS cluster on Fargate

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the EKS cluster will be deployed

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for the EKS cluster

  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: List of Availability Zones for the EKS cluster

  ClusterName:
    Type: String
    Description: Name of the EKS cluster, used as a prefix for resources
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*$'
    ConstraintDescription: Must be a valid DNS-1123 subdomain name

  Environment:
    Type: String
    Description: Environment name, used as a prefix for resources (QA, PROD, PREPROD)
    AllowedValues:
      - QA
      - PROD
      - PREPROD
    Default: QA

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-${ClusterName}-eks-cluster-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks-fargate.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${Environment}-${ClusterName}-eks-cluster"
      Version: "1.27"
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        EndpointPublicAccess: true
        EndpointPrivateAccess: false

  FargateProfile:
    Type: AWS::EKS::FargateProfile
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: !Sub "${Environment}-${ClusterName}-fargate-profile"
      PodExecutionRoleArn: !GetAtt FargatePodExecutionRole.Arn
      Subnets: !Ref SubnetIds
      Selectors:
        - Namespace: default

  FargatePodExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-${ClusterName}-fargate-pod-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks-fargate-pods.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy

Outputs:
  ClusterName:
    Description: The name of the EKS cluster
    Value: !Ref EKSCluster

  FargateProfileName:
    Description: The name of the Fargate profile
    Value: !Ref FargateProfile