# CodeBuild BuildSpec file, this will install all the tools needed to deploy the app

version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - sed -i "s|git@github.com:|https://github.com/|g" .gitmodules
      - git submodule update --init --recursive
      - bash ./submodules/ensolvers-cicd/utils/codebuild_ebs_prebuild_commands.sh

  build:
    commands:
      - bash ./submodules/ensolvers-cicd/deploy-spring-boot-app-to-ebs.sh $MODULES --ignore-aws-vars
