branch-defaults:
  master:
    environment: ${ENVIRONMENT_NAME}
    group_suffix: null
deploy:
  artifact: target/ebs_app.zip
global:
  application_name: ${APPLICATION_NAME}
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
