version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - sed -i "s|git@github.com:|https://github.com/|g" .gitmodules
      - git submodule update --init --recursive
      - bash ./submodules/ensolvers-cicd/utils/codebuild_environment_configuration_commands.sh
    finally:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then
          curl -X POST -d "{'text':':alert-red: AN ERROR OCCURRED DURING \`PRE_BUILD\` PHASE :alert-red:'}" "$SLACK_WEBHOOK_URL"
        fi

  build:
    commands:
      - bash ./submodules/ensolvers-cicd/deploy-react-app-to-s3.sh $REACT_APP_PATH --ignore-aws-vars