AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a generic policy for CodeBuild and attach it to a specific role.

Resources:
  CodebuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"

  CodebuildGenericPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "Codebuild-Generic-Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
              - "codestar-connections:GetConnectionToken"
              - "codestar-connections:GetConnection"
              - "codeconnections:GetConnectionToken"
              - "codeconnections:GetConnection"
            Resource: "*"
      Roles:
        - !Ref CodebuildRole

Outputs:
  CodebuildGenericPolicyArn:
    Description: "ARN of the Codebuild Generic Policy"
    Value: !GetAtt CodebuildGenericPolicy.Arn

  CodebuildRoleArn:
    Description: "ARN of the IAM Role for Codebuild"
    Value: !GetAtt CodebuildRole.Arn